### ISSUE TITLE
Mpc one , Main button not working

### ISSUE THREAD

**Issue by ShoveD01** [TheKikGen/MPC-LiveXplore#35]
Just wondered if anyone had come across buttons failing on the Mpc? 
I have tested the switch and it's ok . 
Is there a hardware test routine?
I have also tried all the usual things, like disconnecting everything , resetting prefs and reinstalling the firmware.

**Comment by air-v** [comment]
Hi, i've got MPC one too. 
Unlit buttons link to the main Force menu. IMO, some buttons should be reassigned to be more efficient in terms of work ergonomics and others are sorely missing, such the selection of the column in Launch mode (No way to delete a column otherwise). Fortunately @Thekikgen is currently working on integrating the Kikpad into the system, which should make our lives easier when using the different editing modes. I admit to being damn impatient.
